### ISSUE TITLE
Keep up the good work...

### ISSUE THREAD

**Issue by stratosgear** [jhawthorn/modelh#1]
Hey John,

I ended up here after reading your [blog post](https://www.johnhawthorn.com/2020/07/modelh-keyboard-controller/) that was posted on HackerNews.

This is really not an issue with your github project, but a word of encouragement to keep up with the project. :)

It seems that you are quite technical and crafty, and really like your approach.

I am also a Model M owner, from an original IBM PS/2 P70 computer I bought in 1989...

I look forward for something published by you that I could buy, order online, or construct myself.

Thanks!

**Comment by jhawthorn** [comment]
Thanks!
